In [1]:
import pandas as pd

df = pd.read_csv("../dataset/StudentsPerformance.csv")

print(df.head())
print("\nColumns:")
print(df.columns)
print("\nShape:")
print(df.shape)

   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard
1  female        group C                some college      standard
2  female        group B             master's degree      standard
3    male        group A          associate's degree  free/reduced
4    male        group C                some college      standard

  test preparation course  math score  reading score  writing score
0                    none          72             72             74
1               completed          69             90             88
2                    none          90             95             93
3                    none          47             57             44
4                    none          76             78             75

Columns:
Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

Shape:
(1000, 8)

In [2]:
df["percentage"] = (
    df["math score"] +
    df["reading score"] +
    df["writing score"]
) / 3

df[["math score", "reading score", "writing score", "percentage"]].head()

   math score  reading score  writing score  percentage
0          72             72             74   72.666667
1          69             90             88   82.333333
2          90             95             93   92.666667
3          47             57             44   49.333333
4          76             78             75   76.333333

In [3]:
def grade(score):
    if score >= 90:
        return "A+"
    elif score >= 80:
        return "A"
    elif score >= 70:
        return "B"
    elif score >= 60:
        return "C"
    elif score >= 50:
        return "D"
    else:
        return "F"

df["grade"] = df["percentage"].apply(grade)

df[["percentage", "grade"]].head()

   percentage grade
0   72.666667     B
1   82.333333     A
2   92.666667    A+
3   49.333333     F
4   76.333333     B

In [4]:
print(df["grade"].value_counts())

grade
B     261
C     256
D     182
A     146
F     103
A+     52
Name: count, dtype: int64

In [5]:
X = df.drop(["math score", "reading score", "writing score", "percentage", "grade"], axis=1)

y = df["percentage"]

X.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course
0,female,group B,bachelor's degree,standard,none
1,female,group C,some college,standard,completed
2,female,group B,master's degree,standard,none
3,male,group A,associate's degree,free/reduced,none
4,male,group C,some college,standard,none

In [6]:
from sklearn.preprocessing import LabelEncoder

le_dict = {}

for col in X.columns:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col])
    le_dict[col] = le

X.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course
0,0,1,1,1,1
1,0,2,4,1,0
2,0,1,3,1,1
3,1,0,0,0,1
4,1,2,4,1,1

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

(800, 5)
(200, 5)

In [8]:
from sklearn.ensemble import RandomForestRegressor

marks_model = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

marks_model.fit(X_train, y_train)

print("Model trained successfully!")

Model trained successfully!

In [9]:
from sklearn.metrics import mean_absolute_error, r2_score

predictions = marks_model.predict(X_test)

mae = mean_absolute_error(y_test, predictions)
r2 = r2_score(y_test, predictions)

print("MAE:", round(mae, 2))
print("R2 Score:", round(r2, 2))

MAE: 11.59
R2 Score: -0.04

In [10]:
import pandas as pd
import numpy as np

np.random.seed(42)

n = 5000

study_hours = np.random.randint(1, 13, n)
attendance = np.random.randint(40, 101, n)
previous_marks = np.random.randint(30, 101, n)
assignments = np.random.randint(20, 101, n)
sleep_hours = np.random.randint(4, 11, n)
mock_test = np.random.randint(20, 101, n)

final_marks = (
    study_hours * 1.5 +
    attendance * 0.2 +
    previous_marks * 0.25 +
    assignments * 0.15 +
    sleep_hours * 2 +
    mock_test * 0.25 +
    np.random.normal(0, 5, n)
)

final_marks = np.clip(final_marks, 0, 100)

df = pd.DataFrame({
    "study_hours": study_hours,
    "attendance": attendance,
    "previous_marks": previous_marks,
    "assignments": assignments,
    "sleep_hours": sleep_hours,
    "mock_test": mock_test,
    "final_marks": final_marks
})

df.head()

,study_hours,attendance,previous_marks,assignments,sleep_hours,mock_test,final_marks
0,7,54,34,90,8,90,75.417793
1,4,59,96,38,4,29,62.090496
2,11,68,40,53,9,85,86.814415
3,8,98,97,97,4,58,90.309679
4,5,81,98,69,6,56,87.062020

In [11]:
def grade(score):
    if score >= 90:
        return "A+"
    elif score >= 80:
        return "A"
    elif score >= 70:
        return "B"
    elif score >= 60:
        return "C"
    elif score >= 50:
        return "D"
    else:
        return "F"

df["grade"] = df["final_marks"].apply(grade)

df.head()

,study_hours,attendance,previous_marks,assignments,sleep_hours,mock_test,final_marks,grade
0,7,54,34,90,8,90,75.417793,B
1,4,59,96,38,4,29,62.090496,C
2,11,68,40,53,9,85,86.814415,A
3,8,98,97,97,4,58,90.309679,A+
4,5,81,98,69,6,56,87.062020,A

In [13]:
X = df.drop(["final_marks", "grade"], axis=1)

y_marks = df["final_marks"]

y_grade = df["grade"]

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train_marks, y_test_marks = train_test_split(
    X,
    y_marks,
    test_size=0.2,
    random_state=42
)

In [15]:
from sklearn.ensemble import RandomForestRegressor

marks_model = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

marks_model.fit(X_train, y_train_marks)

print("Marks model trained successfully!")

Marks model trained successfully!

In [16]:
from sklearn.metrics import mean_absolute_error, r2_score

predictions = marks_model.predict(X_test)

mae = mean_absolute_error(y_test_marks, predictions)
r2 = r2_score(y_test_marks, predictions)

print("MAE:", round(mae, 2))
print("R2:", round(r2, 2))

MAE: 4.19
R2: 0.81

In [17]:
import pickle

pickle.dump(marks_model, open("../model/marks_model.pkl", "wb"))

print("Model saved successfully!")

Model saved successfully!